### ISSUE TITLE
1.18 (and maybe earlier) backport pls

### ISSUE THREAD

**Issue by K4sum1** [AnOpenSauceDev/FastRandom#11]
I'm trying to use the mod in 1.18, and it crashes at launch with this,
`[20:45:32] [main/ERROR]: Mixin apply for mod fastrandom failed nixium.mixins.json:BetterMaths from mod fastrandom -> net.minecraft.class_3532: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Overwrite method method_32855 in nixium.mixins.json:BetterMaths from mod fastrandom was not located in the target class net.minecraft.class_3532. Using refmap fastrandom-refmap.json`

I went through BetterMaths.java and I can't find anything relating to 3532 or 38255. I also don't see a refmap in the source, so I have no idea where these numbers come from.

**Comment by AnOpenSauceDev** [comment]
I probably wont backport this (sorry), go see #12 for more info. As for the class numbers, 3532 is straight up the class that `BetterMaths` does its mixin on (`MathHelper`), and `method_32855` has to do with random Gaussian values.
