### ISSUE TITLE
Faster Random is no longer being *actively* maintained

### ISSUE THREAD

**Issue by AnOpenSauceDev** [AnOpenSauceDev/FastRandom#12]
# What? I thought Faster Random was already dead!
**Yes, and no.** Faster Random was archived because I **_thought_** that it had no performance gain, but looking back i was actually very wrong, and **for random operations, there was a 100x performance boost _on average_.** I plan on releasing a "fix all bugs with 1.3" version of Faster Random (hence me "un-archiving" this mod), and port everything to a newer version of Minecraft. The half-done entity optimizations probably wont be finished by me, purely because i can't be bothered to. 

## Does this mean no more updates still?
**Kind of...** I plan on updating this occasionally to fix bugs, but probably nothing outside of that. 

If anyone wants to take over development, I'll probably give write access and membership on modrinth (as long as I'm sure you wont destroy everything, and are capable of maintaining this mod). But aside from that, expect the occasional bugfix, and possibly a handful of version updates.

**Comment by AnOpenSauceDev** [comment]
I plan to optimize a couple of the random generators at some point, mainly because chunk generation is blocked the most by the following:
- `BaseRandom` (nextInt)
- `CheckedRandom` (next)

**Comment by DeshiDesu** [comment]
Massively underrated mod. Props to you for reviving this mod again 😊

**Comment by AMDYep** [comment]
Has the performance optimization of the mod been measured? I tried the mod, but there was no noticeable change in my fps, mspt, etc.

**Comment by AnOpenSauceDev** [comment]
Most of Faster Random's Random calls are done during world generation, or during events that don't happen every frame. So faster worldgen and better 1% lows on weaker hardware would be noticable. As for the speed of the random system, you should be able to see the objective performance of `Java.util.random` vs `ThreadLocalRandom`, of which I see about 100X faster Floating-point generation.
