### ISSUE TITLE
Amethyst chimes caused by Faster Random v1.3 mod

### ISSUE THREAD

**Issue by Zorklis** [AnOpenSauceDev/FastRandom#13]
Originally reported this on [Reddit](https://www.reddit.com/r/fabricmc/comments/15canod/amethyst_chimes_caused_by_faster_random_v13_mod/) after being archived.
Not sure if it was a mod conflict with anything

**Comment by AnOpenSauceDev** [comment]
I accidentally broke a mixin when writing 1.3, and it played an amethyst sound whenever an entity moved. I'll fix this soon.

**Comment by AnOpenSauceDev** [comment]
fixed in https://github.com/AnOpenSauceDev/FastRandom/commit/409660ed4533bd94628c477c3336c6d10cc1ea38, releasing once i get 1.20.2 working.

**Comment by Zorklis** [comment]
seems to be fixed on 1.4, thanks
