### ISSUE TITLE
Minecraft 1.20.2 support would be appreciated

### ISSUE THREAD

**Issue by Zorklis** [AnOpenSauceDev/FastRandom#14]

**Comment by AnOpenSauceDev** [comment]
fixed with: https://github.com/AnOpenSauceDev/FastRandom/commit/6688e13713ef3f53186a37ad908946b8d19fd407

**Comment by AnOpenSauceDev** [comment]
* released on modrinth now

**Comment by Zorklis** [comment]
Works on 1.20.2
