### ISSUE TITLE
Chunk error

### ISSUE THREAD

**Issue by Minecrafthyr** [AnOpenSauceDev/FastRandom#17]
Seed: -4103198678841418197
/execute in minecraft:overworld run tp @s -45.86 19.00 -12.76 460.65 14.40
![2023-11-09_13 58 04](https://github.com/AnOpenSauceDev/FastRandom/assets/107340726/e1373899-f340-4dfb-a3f6-3fbc4c6c1adf)
/execute in minecraft:overworld run tp @s -130.59 23.50 -28.43 514.20 6.30
![2023-11-09_13 58 35](https://github.com/AnOpenSauceDev/FastRandom/assets/107340726/1d89313c-9bf6-436e-91f4-f7f717a0c2f3)

**Comment by AnOpenSauceDev** [comment]
can you provide a world seed? I'd assume Faster Random would probably cause some terrain changes.

**Comment by Minecrafthyr** [comment]
seed -4103198678841418197
/execute in minecraft:overworld run tp @s -45.86 19.00 -12.76 460.65 14.40

**Comment by AnOpenSauceDev** [comment]
Weird, I'm not getting the same terrain as you, generating again just to be sure.

**Comment by AnOpenSauceDev** [comment]
It looks like cave generation gets randomized, but I'm seeing the same _surface_ terrain here.

**Comment by AnOpenSauceDev** [comment]
Can confirm, ThreadLocalRandom has issues with generation (images below)

> [!NOTE]
> Both images are taken with Faster Random

# World 1
![2023-11-09_15 58 42](https://github.com/AnOpenSauceDev/FastRandom/assets/119765865/f5d97136-fd12-40fa-8489-f948c3482d44)
# World 2
![2023-11-09_15 58 56](https://github.com/AnOpenSauceDev/FastRandom/assets/119765865/7994b646-e279-4309-a6a3-fc99622ac51b)

But at the surface, the actual land lines up 1:1 for me.

**Comment by AnOpenSauceDev** [comment]
Non-cave terrain generation is unaffected though (notice how the lava and azalea trees randomly vanish).

# World 1, again
![2023-11-09_16 05 53](https://github.com/AnOpenSauceDev/FastRandom/assets/119765865/1f7d4259-9d60-4c4f-b027-6ab959c1423e)
# World 2, again
![2023-11-09_16 06 08](https://github.com/AnOpenSauceDev/FastRandom/assets/119765865/3927aa41-95ba-48f5-9ae5-feb9a9904805)

**Comment by AnOpenSauceDev** [comment]
* structure generation is not affected at all.

**Comment by Minecrafthyr** [comment]
> It looks like cave generation gets randomized, but I'm seeing the same _surface_ terrain here.

I'm using a new seed that's different from the one issue was created with.

**Comment by AnOpenSauceDev** [comment]
> > It looks like cave generation gets randomized, but I'm seeing the same _surface_ terrain here.
> 
> I'm using a new seed that's different from the one issue was created with.

I know, I was just pointing out that terrain is unaffected outside of caves.

**Comment by AnOpenSauceDev** [comment]
> I'm using a new seed that's different from the one issue was created with.

I'm not actually referring to that at all, it turns out that caves are randomized differently every time you make a new world with Faster Random. And I'm not getting that "chunk-error" to pop up, so that might be a problem with vanilla mc.

**Comment by AnOpenSauceDev** [comment]
Closing and pinning, as there isn't really much I can do to fix this.

**Comment by Rozbiynk** [comment]
i have same issue, it also can be viewed using worldeditor's "regenerate" function

**Comment by Rozbiynk** [comment]
but i hope it was fixed in 2.0

**Comment by AnOpenSauceDev** [comment]
> but i hope it was fixed in 2.0

Yes and No, cave terrain generation is much more consistent (sometimes even at parity with vanilla with carver shapes), but stuff like ore generation and feature placement is now off compared to vanilla. Overall, there should be way less "broken" caves that spawn in.

**Comment by Rozbiynk** [comment]
yeah i mostly mean this ugly chunked generation, it also very annoying in the nether

**Comment by AnOpenSauceDev** [comment]
Because of how Faster Random works (both pre and _post-2.0.0_), everything has their randomization modified. Having edge-cases for everything 1) takes time to develop, and 2) reduces our potential performance uplift, especially for worldgen. I've said this for #20  as well. It's possible, and [Francium](https://modrinth.com/mod/francium-optimization) does this as well, but on an older version of Minecraft, where this is much easier to do.

**Comment by Rozbiynk** [comment]
> > but i hope it was fixed in 2.0
> 
> Yes and No

no it wasnt fixed. First screen is faster random 2.0 + c2me, second is c2me without fast random third screen is faster random without c2me
![2024-01-13_15 31 32](https://github.com/AnOpenSauceDev/FastRandom/assets/95433246/1f6b02db-2f04-4381-851c-408aeb5576a9)
![2024-01-13_15 40 22](https://github.com/AnOpenSauceDev/FastRandom/assets/95433246/a9398b25-c9da-4af8-a319-5970f9f576f6)
![2024-01-13_15 46 18](https://github.com/AnOpenSauceDev/FastRandom/assets/95433246/902c3448-3d7b-432a-8954-49b5623d6b1c)

**Comment by AnOpenSauceDev** [comment]
> no it wasnt fixed.

What I meant by "Yes and No," was that terrain generates _like_ vanilla, but is not 1:1 for generation. Also, because of how the random system works, there is no difference with/without c2me, as the seed for cave terrain will be randomized the same way.

**Comment by GopsRay** [comment]
Hlo I just want to clarify this [NOTE: Faster random alters world generation for caves in a subtle (3.0.0+) way, due to some limitations with ThreadLocalRandom and L64X128MixRandom. Structure placement (villages, strongholds, ancient cities) is not affected. If you are willing to accept this and compromise for much faster worldgen and random logic, then this is for you!] 
Does this problem 'alters world generation' is fixed or never be fixed?

**Comment by AnOpenSauceDev** [comment]
I doubt that the world generation can **fully** 1:1 match vanilla, but with every major update we get much closer to vanilla parity for features. This issue was specifically about some cave generation being really broken at chunk borders in older versions of Faster Random, which has been fixed.

**Comment by GopsRay** [comment]
That means in the latest version of [Faster Random 3.0.4] cave generation is not 1:1 same as vanilla world cave generation.

**Comment by AnOpenSauceDev** [comment]
Technically it's not direct cave generation, but it's the location of some types of cave carvers in 3.0.0+. The caves themselves generate as they should.

**Comment by GopsRay** [comment]
Soory,I cant't understand this properly do u mean vanilla cave generation and faster random cave generation are not the same?

**Comment by GopsRay** [comment]
My english is not good and soory if you think I'm annoying :( but can pls clarify this doubt [vanilla cave generation and faster random cave generation are not the same]

**Comment by GopsRay** [comment]
Can pls clarify this doubt [vanilla cave generation and faster random cave generation are same (or) not same]

**Comment by GopsRay** [comment]
Can pls clarify this doubt [vanilla world and cave generation and faster random cave generation are same (or) not same]

**Comment by AnOpenSauceDev** [comment]
It's close to vanilla, but is not exactly vanilla. If you're speedrunning, the run would not be approved, but aside from that you will not notice anything 99% of the time. There's nothing else I can really say to clarify this. 

If you have anything else to say please make a new [Discussion](https://github.com/AnOpenSauceDev/FastRandom/discussions) so people do not get tonnes of notifications.
