### ISSUE TITLE
A toggle for worldgen-affecting optimizations

### ISSUE THREAD

**Issue by HyperSoop** [AnOpenSauceDev/FastRandom#20]
If it's not too much of a hassle it would be neat to have a config file allowing one to toggle optimizations that affect worldgen (if it'd be sensibly possible to implement into the mod)

**Comment by AnOpenSauceDev** [comment]
I'll see what i can do, but **this will likely result in a lot of cases where the worldgen engine will not see any major speed up.** (currently Faster Random overrides random _no matter what,_ which leads to the aforementioned terrain problems.)

**Comment by AnOpenSauceDev** [comment]
Looking into what random calls Minecraft makes, a lot of the cave worldgen code relies on the functions I've replaced, and manually checking and disabling all the worldgen-related random calls is very time consuming. Adding to that, **Faster Random is nowhere near as "fast" when worldgen is forced to use the legacy random.** (especially when on a sever) which doesn't make me see this as a worthwhile addition.

**Comment by HyperSoop** [comment]
Fair enough, I'll close the issue then.
