### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by Sunconure11** [AnOpenSauceDev/FastRandom#22]
https://pastebin.com/AtpB9BVN

**Comment by AnOpenSauceDev** [comment]
Replaced the mod .jar on modrinth with a fixed version, for some reason the entity mixin wasn't removed from my build when i pulled. Let me know if that fixes anything

**Comment by Sunconure11** [comment]
Seems to work

**Comment by Steveplays28** [comment]
nice!
