### ISSUE TITLE
Solid block rotation glitch

### ISSUE THREAD

**Issue by theprodigy2013** [AnOpenSauceDev/FastRandom#23]
[1.20.1, Fabric]
Hey, 
Since the 2.0.0 version, there's this weird visual glitch where after you update (destroy/place on) a solid block, solid blocks around it in a small radius change their rotation(?) randomly. Some blocks are non-rotatable but they still somehow do. It doesn't affect transparent/foliage blocks like grass or leaves.
I don't know whether that's a standalone or incompatibility issue, since i didn't really test it out in vanilla environment. I've only managed to figure out that with FR disabled this doesn't happen, maybe it's some other mod acting funny.

https://github.com/AnOpenSauceDev/FastRandom/assets/150455861/ebdc1d85-25e7-4e22-b721-8733d940de9c

**Comment by AnOpenSauceDev** [comment]
I can replicate this, it seems to affect 2.0.0 and up, and only affects the chunk you're in. I'll try exclusively disabling Faster Random for blockstate placement, and see if it works.

**Comment by AnOpenSauceDev** [comment]
I unfortunately won't be able to work on this issue on a Minecraft-capable computer for a while, so a quick fix is to just downgrade to 1.6.0 for now. I'll un-feature 2.0.0 for now, as this is a pretty big issue.

**Comment by Steveplays28** [comment]
I can look into it.

**Comment by Andriymixx** [comment]
Hi, I also experienced this issue when I place or destroy blocks. Futhermore, it is much more noticeably with "LambDynamicLights" mod which I think also updates blocks in raduis. Hope this info will help you.

https://github.com/AnOpenSauceDev/FastRandom/assets/120801944/d60e1f62-451c-424d-b624-247be6bbe5b4

**Comment by Kasualix** [comment]
Seeds of Random are undoubtedly an integral part of the game. Considering how Faster Random works and the nature of ThreadLocalRandom, I think this is unfixable. It's better to make some sacrifices, go back to the [1.6.0](https://modrinth.com/mod/faster-random/version/1.6.0) status and archive [2.0.0](https://modrinth.com/mod/faster-random/version/2.0.0).

**Comment by Steveplays28** [comment]
Not unfixable, in a way. The random optimisation can be disabled for certain things such as block placement. Need to get around to it though.

**Comment by Steveplays28** [comment]
@AnOpenSauceDev Hi AnOpenSauceDev, I fixed this and implemented the `L64X128MixRandom` RandomGenerator.
I'll create a PR. It does create a new instance of the object every time the seed is set, but as far as I have tested and profiled so far, this is faster than using `ThreadLocalRandom` by about 4x (I tested against Faster Random `v2.0.0`).

**Comment by AnOpenSauceDev** [comment]
Awesome! I just got my hands on a Steam Deck, so I should be able to try testing the fix overseas on a handful of things I suspect might also be affected by 2.0.0.

**Comment by Steveplays28** [comment]
Cool! I fixed the arrow rendering as well, but it still seems slightly inconsistent. Not sure why though, even after debugging. I made all the arrow rendering use a consistent seed and the normal Java `Random` implementation.

**Comment by andreasdc** [comment]
BTW did you benchmark the changes? Some classes from original MathHelper were faster than FastRandom when I checked it some time ago.

**Comment by Steveplays28** [comment]
Yeah, I checked with VisualVM. It's significantly faster with my PR above.

**Comment by andreasdc** [comment]
And what is this thing that moves arrows and blocks? What's the reason are they even updating? Shouldn't they be solid?

**Comment by Steveplays28** [comment]
I fixed that in my PR as well. The issue was that stuck object rendering (e.g. stuck arrows) use a random `int` and some random `float`s to determine the model part they're attached to, and the direction they're facing.
The seed for this wasn't being set properly, so I had to replace it with Java's `Random` with a set seed.

**Comment by andreasdc** [comment]
All right, but if blocks are "refreshing" so fast that it glitches, what is happening? Shoudn't they be solid?

**Comment by Steveplays28** [comment]
The seed for the new random generator wasn't being set, causing the block textures to change every time you placed a block. In my PR the seed is now set, by creating a new random generator instance with the correct seed used by the block placement (and other functions).

**Comment by andreasdc** [comment]
Ok, but you didn't have to place a block to let it happen, it was happening during running or all block changes in the chunk did that?

**Comment by AnOpenSauceDev** [comment]
Odd, running never changed block rotation for me, so I assume that some block update must have occured while you were running. It could be flowing water, but i haven't tested that.

**Comment by Poopooracoocoo** [comment]
Could you consider marking 2.0.0 as beta/alpha or archiving it?

**Comment by AnOpenSauceDev** [comment]
> Could you consider marking 2.0.0 as beta/alpha or archiving it?

I'll go ahead and do that.

**Comment by AnOpenSauceDev** [comment]
This issue is now fixed. I'll be releasing this as a major version on Modrinth, as it will create some structure and cave differences in worlds generated with pre-#25 worlds.

**Comment by AnOpenSauceDev** [comment]
This fix is now available as [3.0.0](https://modrinth.com/mod/faster-random/version/3.0.0) on Modrinth!
