### ISSUE TITLE
Enchantment Unpredictability

### ISSUE THREAD

**Issue by Fishvap** [AnOpenSauceDev/FastRandom#26]
This mod is causing enchanting to become highly unpredictable and random, causing the table to roll infinitely without actually holding anything, so it's like gambling / rolling the dice with what you're going to get.

**Comment by AnOpenSauceDev** [comment]
Looking into the bug, it seems that enchantments get rerolled twice. I'm working on a fix that will somewhat solve this, and also bring the enchantment results much closer to vanilla.

**Comment by AnOpenSauceDev** [comment]
Looking into what happens, the enchantments _are actually generated correctly,_ however minecraft completely ignores the result and generates garbage when you physically press the button.
