### ISSUE TITLE
Sodium incompatibility/Vanilla crash on startup

### ISSUE THREAD

**Issue by theprodigy2013** [AnOpenSauceDev/FastRandom#30]
[1.20.1]
Both new versions, 3.0.0 and 3.0.1 are incompatible with the 0.5.8 Sodium
Log: https://mclo.gs/08oykVt

**Comment by theprodigy2013** [comment]
Also without Sodium it seems to crash the game on launch. 
Log: https://mclo.gs/4LBcvmg

**Comment by Steveplays28** [comment]
You're using a JVM which doesn't implement the `L64X128MixRandom` `RandomGenerator`.
Could you try using a different JDK/JRE, such as [GraalVM](https://www.graalvm.org/)?

**Comment by theprodigy2013** [comment]
Yeah, works just fine with GraalVM, had an Adoptium distro before. So this version is incompatible with Adoptium distros?

**Comment by Steveplays28** [comment]
Maybe you specifically need a specific version of OpenJDK?
Not sure myself, I'll do some investigating.

Might be worth adding a better warning/disabling the mod if an unsupported JDK is detected.

**Comment by AnOpenSauceDev** [comment]
Interesting, I thought LXM was part of the Java 17 standard? I'll add a disclaimer the modrinth page.

**Comment by AnOpenSauceDev** [comment]
> Yeah, works just fine with GraalVM, had an Adoptium distro before. So this version is incompatible with Adoptium distros?

Actually, no?
Turns out I was using an even older version of Adoptium on my computer, yet it works fine both in- and outside of development environments. No idea what's going on there.

**Comment by theprodigy2013** [comment]
I was using JRE as it's a bit lighter than JDK, out of the box distro, no tweaks no changes. I tried disabling all JVM arguments but the outcome was the same.
