### ISSUE TITLE
Warn if JDK is unsupported

### ISSUE THREAD

**Issue by Steveplays28** [AnOpenSauceDev/FastRandom#31]

**Comment by AnOpenSauceDev** [comment]
We can do this in 3 ways:
1. Warn the user pre-launch before Faster Random loads the classes with the `RandomGenerator`'s
2. Use a mixin plugin to disable all of Faster Random's functionality, then pop up a screen with the warning (useless on servers though)
3. Forcefully crash MC with a more obvious warning. 

Not sure what would get the message across the best.

**Comment by AnOpenSauceDev** [comment]
3.0.2 implements 1 and 3

**Comment by AnOpenSauceDev** [comment]
I have made a JDK warning as of https://github.com/AnOpenSauceDev/FastRandom/commit/816f7cec1e102cbdf9988855e8ac5a55056ed2c7, but I'm not sure of a known broken JDK.
