### ISSUE TITLE
[OTHER]: Update Readme to reflect cave caveat is only on older versions

### ISSUE THREAD

**Issue by alexweber** [AnOpenSauceDev/FastRandom#35]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

The caveat that caves generate differently is enough to make a lot of people mnot use this mod.  However it's apparently been fixed in 2.0... should probably mention that a little more clearly on the front page... ie: README....

**Comment by AnOpenSauceDev** [comment]
Not quite, Caves generate **very similarly** to vanilla now, but not 1:1. So while this is usually imperceptible, I'm going to leave the notice up anyways.
