### ISSUE TITLE
Mod icon isn't square which causes issues with Mod Menu - Errors in Minecraft log

### ISSUE THREAD

**Issue by Flavio6561** [AnOpenSauceDev/FastRandom#37]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

The icon of the mod is not a perfect square (it is 317x330), so as soon as you open mod menu it creates annoying long errors about the fact that it isnt a square, and therfore it doesnt show up the logo in mod menu either.
Could you please fix this by resizing the icon? Thanks

![Log](https://github.com/AnOpenSauceDev/FastRandom/assets/150461739/2f64e2d7-fe13-4e8c-af3c-5e64f72a157f)

**Comment by Steveplays28** [comment]
Hi @Flavio6561, thanks for the report. Just made a fix for this.
