### ISSUE TITLE
Same bugged image

### ISSUE THREAD

**Issue by Flavio6561** [AnOpenSauceDev/FastRandom#39]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

Hi, the issue with image dimension (https://github.com/AnOpenSauceDev/FastRandom/issues/37) is still present after the update...
Dimension of the image and the error in the log are the same, and in mod menu the image is not showing up.

**Comment by AnOpenSauceDev** [comment]
I built it with the new image? I'll reupload anyways.

**Comment by AnOpenSauceDev** [comment]
Okay, just re-released 3.0.3. This 100% has the fix.
