### ISSUE TITLE
Optimize Entity.class breaks on 1.19.4

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [AnOpenSauceDev/FastRandom#4]
Seems like the Mixin for Entity.class random optimization is 1.20-specific. Any plans to make a port for 1.19?

**Comment by AnOpenSauceDev** [comment]
> Seems like the Mixin for Entity.class random optimization is 1.20-specific. Any plans to make a port for 1.19?

I do plan on bringing it to 1.19, but haven't figured a good way port it yet (which is why its not on modrinth yet). The big issue is because the classes are probably different.

**Comment by QuanTrieuPCYT** [comment]
Try making two seperate branches for two versions I guess.

Upon inspection I found out that the only thing that broke the mixin is the redirect of the `playAmethystChimeSound` method. Commenting the code made the mixin worked for my case, seems like we need different approach for the lower version though.
