### ISSUE TITLE
[BUG]: java security doesn't let this run but never warns or gives a crash.

### ISSUE THREAD

**Issue by davidromrell** [AnOpenSauceDev/FastRandom#40]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Does your system support Faster Random?

- [x] I have checked that my JVM supports Faster Random 3.0.0+.

### Issue description.

I am using a secure java environment so it does not let this work fully although gives no crash or bug just lag, what would you recommend.

### Issue replication.

on startup JDK 21 
with game startup java 17

mod version is 3.03

**Comment by davidromrell** [comment]
the actual version of java Minecraft decided to use is 17.

**Comment by AnOpenSauceDev** [comment]
I'm not exactly sure by what you mean when you say "java security", and I don't see how it could break Faster Random since it doesn't import anything external except for MixinExtras. I'm going to need more information about your Java setup so I actually understand what's going on here.

**Comment by davidromrell** [comment]
jdk-21.0.2.13 is my java base version, it has had an issue where it says corrupted or invalid jar file, yet it runs all the other mods fine. Unsure what else to add.

**Comment by AnOpenSauceDev** [comment]
Maybe Corretto doesn't support RandomGenerator, and tries to preload the class, breaking the mod. Try using GraalVM.

**Comment by davidromrell** [comment]
I will try fixing this in about a week, let me know if you find a solution before than. Thanks for your time.

**Comment by davidromrell** [comment]
I tested and it ran with GraalVM and it works.

**Comment by davidromrell** [comment]
Could you show where the learning happened that caused this incredible mod? I would like to learn.

**Comment by AnOpenSauceDev** [comment]
> Could you show where the learning happened that caused this incredible mod? I would like to learn.

At a basic level, it's nothing complex, originally this mod just hijacked the `MathHelper` random methods and essentially replaced them with calls to `ThreadLocalRandom`, as it was faster than the `CheckedRandom` implementation. Over time I extended this to some entity operations, and nowadays the `Random` interface itself has been re-implemented with a much faster random generator (LXM) that comes built in with a handful of JDK's (unfortunately quite a few do not contain these generators).
