### ISSUE TITLE
[BUG]: version 4.0.0 has FPS drop when entering world.

### ISSUE THREAD

**Issue by davidromrell** [AnOpenSauceDev/FastRandom#44]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Does your system support Faster Random?

- [X] I have checked that my JVM supports Faster Random 3.0.0+.

### Issue description.

3.0.4 did not have this problem, unsure what you changed.

### Issue replication.

enter a world with just your mod using 4.0.0 on 1.20.1 fabric

**Comment by AnOpenSauceDev** [comment]
I cannot replicate this lag on Fabric/Quilt 4.0.0.

**Comment by davidromrell** [comment]
its literally only for the first 30 seconds to a minute so you have to instantly check fps.

**Comment by AnOpenSauceDev** [comment]
Isn't that how joining a world works? My performance is always at ~90FPS after immediately joining both with and without Faster Random, before hitting ~1000 when all the chunks get built.

**Comment by davidromrell** [comment]
something in your mod is making the world joining worse and significant decrease to gains in performance, I am not the maker of this mod so i cannot say what.

**Comment by AnOpenSauceDev** [comment]
Nothing has changed? We just use nextLong instead of nextInt for feature generation, there shouldn't be any noticeable difference. In fact, performance should be better because of the laggy `ChunkRandom` workaround being removed.

**Comment by davidromrell** [comment]
Agreed that is why I was surprised.

**Comment by acerola0rion598** [comment]
I tried creating a world and tp-ing to not generated chunks, when I'm at 32 render distance I hit ram limit faster and have less fps with 4.0.0 (than with 3.0.4), tho if I reduce the render distance so it doesn't hit the ram limit with 4.0.0 chunks are actually generated faster. So I don't think it's the dev's fault

**Comment by davidromrell** [comment]
I do not know what is causing it just know that I am experiencing fps drop with his mod. I will check to see if the fabric version changed or something.

**Comment by davidromrell** [comment]
it looks like it is the new fabric 1.15.9 changed to 1.15.10 and the mod change together decrease mod performance unsure how much is his mod compared to fabric change.

**Comment by davidromrell** [comment]
1. I accidentally changed java arguments 2. fabric had a version change which altered the performance gains from javaArgs and mod I believe due to altering render distance in some way. 3. My launcher had a bug in which it downgraded which file i was using.

**Comment by AnOpenSauceDev** [comment]
>  GC i think is getting triggered by removing ChunkRandom.

ChunkRandom isn't removed in 4.0.0, we just don't force ChunkRandom to use a slower random in order to prevent some mods from crashing anymore (because we fixed it in 4.0.0 :) ). Chances are, your ram is being flooded with new chunks, and you'll have to dedicate more RAM to not lag from all the GC.

**Comment by davidromrell** [comment]
my minecraft doesn't have the 
>That sounds like average Minecraft, as AnOpenSauceDev said.
 experience due to java arguments. 

>The vanilla chunk manager blocks the server thread when loading chunks for players 
Sorta true, with my java args it is false, with "average minecraft" it is true.

**Comment by davidromrell** [comment]
As I stated fabric altered rendering distance:
 > Chances are, your ram is being flooded with new chunks, and you'll have to dedicate more RAM to not lag from all the GC.
