### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by davidromrell** [AnOpenSauceDev/FastRandom#45]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

1. less heavy of a mod 
2. instead of improving on fast placement can you make the random code itself faster and/or make your current solution more robust?
3. Could be "average Minecraft" though it seems this mod has a minor issue similar to what is trying to be solved by the mod "dynamic FPS".

**Comment by Steveplays28** [comment]
This mod is not heavy at all. It contains 1 mixin and a custom implementation of Minecraft's `Random` class, using `RandomGenerator` (see `RandomGeneratorRandom`). This new implementation of random number generation is a lot faster than what's used in vanilla (legacy `java.util.Random`).
I'm not sure what Dynamic FPS does, haven't looked into it.

**Comment by davidromrell** [comment]
I want to use this mod and noisium! Right now it barely fits my specifications, and I may end up switching to other mods instead.

**Comment by Steveplays28** [comment]
Faster Random is compatible with Noisium

**Comment by AnOpenSauceDev** [comment]
Also, Dynamic FPS does not do anything similar to Faster Random in the slightest. Dynamic FPS slows down your game so Minecraft doesn't eat up more resources when idle. Faster Random optimizes the RNG system.

**Comment by DJR-dev** [comment]
Could you optimize calls to worldgen_region_random as well.

**Comment by SoBeeIt** [comment]
Can you optimize worldgen_region_random calls?

**Comment by AnOpenSauceDev** [comment]
I could, but I don't want to screw up worldgen too much, or create so many new generators that the improvement is negligible. What I could do is have a version of Faster Random that completely breaks parity, and uses random in a way that yields much more performance.
