### ISSUE TITLE
[BUG]: 5.0.0 incompatible with java 17 (aka it can't work on minecraft 1.20.1)

### ISSUE THREAD

**Issue by mxnmnm** [AnOpenSauceDev/FastRandom#55]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Does your system support Faster Random?

- [X] I have checked that my JVM supports Faster Random 3.0.0+.

### Issue description.

5.0.0 is not compatible with java 17

### Issue replication.

Try to run 5.0.0 on minecraft 1.20.1 with java 17

### Log File / Crash Report (if applicable)

https://gist.github.com/mxnmnm/907bf0c363fef37dee5ab3ce4fe385d5

**Comment by AnOpenSauceDev** [comment]
Can't Java 21 be run with 1.20.1?

**Comment by AnOpenSauceDev** [comment]
Try running the artifact from [that new action](https://github.com/AnOpenSauceDev/FastRandom/actions/runs/9906866536/job/27369332312), and let me know if it works for your system.

**Comment by AnOpenSauceDev** [comment]
I just released 5.0.1, which has less strict JDK requirements (which should let you play normally).

Re-open if another JDK version bug happens here.
