### ISSUE TITLE
[OTHER]: System Requirements Explanation Guide

### ISSUE THREAD

**Issue by MihanDeNoob** [AnOpenSauceDev/FastRandom#58]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Issue description.

For lesser beings such as my self. 
Although i think i figured it out (downloaded GraalVM, changed java.exe in launcher to use java.exe from GraalVM in bin folder.) since i can see Faster Random in the modlist.

**Comment by AnOpenSauceDev** [comment]
The guide is more for people who get the error about Faster Random not being able to enable the generator in their logs. _Most_ of the time, everything works fine (I'm pretty sure the bundled JDK in the default non-server launcher works).

I could probably still clarify this stuff in the description to be clearer.

**Comment by AnOpenSauceDev** [comment]
I have made some changes in the description to clarify who actually needs to follow them (as the default JDK from the Minecraft Launcher should work).
