### ISSUE TITLE
[BUG]: "Mods not found" error with NeoForge Alpha of Faster Random

### ISSUE THREAD

**Issue by Diamondback88** [AnOpenSauceDev/FastRandom#59]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Does your system support Faster Random?

- [X] I have checked that my JVM supports Faster Random 3.0.0+.

### Issue description.

When I use NeoForge version 47.1.106 (1.20.1) to boot with the NeoForge alpha of Faster Random, I receive an error saying that the mod file has mods that were not found.

### Issue replication.

1. Install NeoForge 47.1.106 and the NeoForge alpha of Faster Random.
2. Launch the game and receive the error.

### Log File / Crash Report (if applicable)

https://mclo.gs/xaYXtqb

**Comment by AnOpenSauceDev** [comment]
It looks like the `mods.toml` is broken, and I don't know at what point it stopped working. I wouldn't recommend using the neoforge version if you can, and instead just use [connector](https://modrinth.com/mod/connector) to load the latest Faster Random (which is faster and way closer to vanilla generation).

**Comment by Diamondback88** [comment]
Do you know what client-side overhead Sinytra adds to a modpack when loaded? I noticed it adds like 50+ mods to your mod count (likely all the Fabric libraries), but does the performance hit from Sinytra + the fabric libraries offset the client performance gained from Faster Random? I'll also do some digging about this in the Sinytra discord.

**Comment by AnOpenSauceDev** [comment]
People seem to think that more mods inherently reduces performance, when in reality it's a _tiny_ amount of code in RAM that usually isn't even compiled unless needed by another mod. I also don't think that the Fabric API has that much of an overhead in the things it does run.

**Comment by Diamondback88** [comment]
Perfect, I didn't realize they weren't compiled if they're not needed at runtime. I'll check it out!
