### ISSUE TITLE
[BUG]: Chicken crash (mod conflict?)

### ISSUE THREAD

**Issue by mxnmnm** [AnOpenSauceDev/FastRandom#60]
### Does an issue already cover this?

- [X] I have searched for any existing issues, and didn't find any.

### Does your system support Faster Random?

- [X] I have checked that my JVM supports Faster Random 3.0.0+.

### Issue description.

Chickens randomly crash on my server. Neruina caught it so it didn't actually crash and I just put in the error it gave me.

### Issue replication.

We just have multiple chickens crammed in a space for egg production and they very occasionally crash. Not sure how many other mods and such are involved.

### Log File / Crash Report (if applicable)

https://gist.github.com/mxnmnm/4948b04b62efd7a7ca17b63f8e09ae74

**Comment by AnOpenSauceDev** [comment]
Looking at the source code for MC, it doesn't look like this is possible in vanilla (nothing that's relevant to the chicken calls with a bound that could become negative). This is likely a mod conflict of some sort, but I don't know what mods you have running.

**Comment by mxnmnm** [comment]
I am running A LOT of other mods and I'm not sure how to consistently reproduce the issue in a way that's testable within a reasonable amount of time :/

**Comment by mxnmnm** [comment]
Other than your standard binary search do you have any ideas of what mods might be causing this? I'll send a list of the mods I have but considering how many there are I'm not sure it'll be that helpful

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/1cb1f8d192b17fa377b45cec84500c03

**Comment by AnOpenSauceDev** [comment]
I don't really know what it could be. All the stacktrace you have really says is "something called aiStep() on a chicken and made Faster Random generate a negative number." Using GitHub's code search showed nothing, so chances are it's a smaller/closed-source mod that I probably won't be able to track down, and Neruina doesn't give enough information on what is adding the offending `nextInt()` call.

In Minecraft's source, `nextInt` is only called once with a constant, positive bound within the whole method hierarchy for `tickMovement()/aiStep()`, so I'm sure that some lesser-known mod is causing this. I'm closing as 'not planned' for now, as this might not even be a bug with Faster Random itself.

**Comment by mxnmnm** [comment]
So some more interesting info: This only happens on dedicated servers

**Comment by AnOpenSauceDev** [comment]
The chicken logic would only occur server-side anyways. But this should be triggerable in singleplayer/LAN too.
