### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [AnOpenSauceDev/FastRandom#61]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by AnOpenSauceDev** [comment]
Faster Random is licensed under Apache 2.0, so you're fine to put this mod in your modpack as long as you attribute the mod dev. 

Furthermore, this means any mod with a permissive license like BSD, MIT, Apache, etc can be put in a modpack as long as you provide credit.
