### ISSUE TITLE
Modrinth images should be switched

### ISSUE THREAD

**Issue by Zorklis** [AnOpenSauceDev/FastRandom#7]
![stats](https://github.com/AnOpenSauceDev/FastRandom/assets/85455465/9ed6ce04-309f-4add-b360-5ea63974ae92)
Currently this image shows an "_**after and before**_", while the text below says "823 FPS **Before** FastRandom -> 909 FPS **After** FastRandom"
so it's a weird way to present same info in two different ways and should be unified with a progressive before to after.

**Comment by AnOpenSauceDev** [comment]
yeah that's a big mistake on my part.

**Comment by AnOpenSauceDev** [comment]
Now that Faster Random is no longer archived, I've realized that the whole "benchmark screenshot" is very misleading, as the mod's performance gain is much more significant during high load or sudden lagspikes, so I'm just going to remove it at this point.
