### ISSUE TITLE
Faster Random 1.2 crashes when world load is done

### ISSUE THREAD

**Issue by Zorklis** [AnOpenSauceDev/FastRandom#8]
Issue: Fast Random - 1.1 worked fine with every mod.
Updated to 1.2 and seemed like no issues at first, until I selected my world save and it began to show the loading screen and when it was done.. it crashed. tried more than once.

I'm on MC 1.20.1, Fabric 
Crash report: [crash-2023-07-19_11.27.18-server.txt](https://github.com/AnOpenSauceDev/FastRandom/files/12092811/crash-2023-07-19_11.27.18-server.txt)

**Comment by AnOpenSauceDev** [comment]
i screwed up on commit https://github.com/AnOpenSauceDev/FastRandom/commit/6651f88f1e26b94a0c15f42bab8c26d37332dc75, because i forgot to also unify MobEntity.  <br>
download a slightly earlier build from github actions if you need to.

**Comment by AnOpenSauceDev** [comment]
fixed with 1.3... sort of?
